### ISSUE TITLE
Crash during compilation, `not implemented: Unary`

### ISSUE THREAD

**Issue by pushchris** [Dwlad90/stylex-swc-plugin#9] opened 2024-08-30 22:04 UTC
Hello! Hoping you can help us track down what might be causing this plugin to crash. Tried switching out the Babel version for this using almost the exact settings you have in the example project. The example project runs fine on our machines, but for some reason pulling it into a PNPM mono-repo doesn't work quite right. As it's loading it spits out a couple of errors for every single file it tries to compile. Have confirmed that `swc_core` is exactly the same in our project vs the example so that appears to maybe be a misdirect. Any ideas on what we can try?

Error 1
```
thread '<unnamed>' panicked at src/shared/utils/js/evaluate.rs:479:23:
not implemented: Unary
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '' panicked at /Users/geist/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs:166:14:
failed to invoke plugin: failed to invoke plugin on 'Some("/project/@packages/ui/global/stylex/vars.stylex.ts")'

Caused by:
    0: failed to invoke `/project/node_modules/.pnpm/@stylexswc+swc-plugin@0.2.0/node_modules/@stylexswc/swc-plugin/dist/stylex_swc_plugin.wasm` as js transform plugin at /project/node_modules/.pnpm/@stylexswc+swc-plugin@0.2.0/node_modules/@stylexswc/swc-plugin/dist/stylex_swc_plugin.wasm
    1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
    2: RuntimeError: unreachable
```

Error 2
```
 ○ Compiling /[locale]/index/[date] ...
thread '<unnamed>' panicked at src/shared/utils/core/stylex_merge.rs:96:18:
Illegal argument
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '' panicked at /Users/geist/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs:166:14:
failed to invoke plugin: failed to invoke plugin on 'Some("/project/@apps/web/src/components/NavigationLoading/NavigationLoading.tsx")'

Caused by:
    0: failed to invoke `/project/node_modules/.pnpm/@stylexswc+swc-plugin@0.2.0/node_modules/@stylexswc/swc-plugin/dist/stylex_swc_plugin.wasm` as js transform plugin at /project/node_modules/.pnpm/@stylexswc+swc-plugin@0.2.0/node_modules/@stylexswc/swc-plugin/dist/stylex_swc_plugin.wasm
    1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
    2: RuntimeError: unreachable
```

next.config.js
```
const path = require("path");
const stylexPlugin = require("@stylexswc/nextjs-plugin");
const config = {
  productionBrowserSourceMaps: process.env.NODE_ENV === "development",
  trailingSlash: true,
  transpilePackages: [
    "@packages/sdk",
    "@packages/ui",
    "@packages/i18n",
    "@packages/analytics",
  ],
  experimental: {
    swcPlugins: [[
      "@stylexswc/swc-plugin",
      {
        "dev": process.env.NODE_ENV === "development",
        "runtimeInjection": false,
        "genConditionalClasses": true,
        "treeshakeCompensation": true,
        "unstable_moduleResolution": {
          "type": "commonJS",
          "rootDir": path.join(__dirname, "../.."),
        }
      }
    ]],
  }
};

module.exports = stylexPlugin({
  rootDir: path.join(__dirname, "../.."),
})(config);

```

**Comment by Dwlad90** [comment] 2024-09-03 17:14
@pushchris 
Hi, thank you so much for finding the bugs. I will try to fix them in a few days.

As far as I can understand from the error stack, the problem is not related to the versions of the packages, but lies directly in the compilation of the code.
Could you provide a little more information about this problem. I would be grateful if you could provide the code of the following files from your project:
1) /project/@packages/ui/global/stylex/vars.stylex.ts
2) /project/@apps/web/src/components/NavigationLoading/NavigationLoading.tsx

or a link to a sandbox with minimal reproduction of the error.

**Comment by pushchris** [comment] 2024-09-06 18:18
Well, have been trying to build a small reproducible example for you and can't stop getting https://github.com/Dwlad90/stylex-swc-plugin/issues/10 such that this error appears in a smaller context. Hopefully once that one is resolved can get you something! 

The error happens for every single file that uses StyleX in the entire project, it's not contained to just the one I provided in the example.

**Comment by Dwlad90** [comment] 2024-09-06 20:27
@pushchris,

Next week I will return to work on the project and will try to fix all known issues as soon as possible. I hope that after the fixes you will be able to fully start using this plugin.

**Comment by Dwlad90** [comment] 2024-09-10 21:02
Hi @pushchris,

A new release of the plugin with a fix has been uploaded to NPM.

In the PR #19, a bug in processing an unary expression has been fixed, and error messages have been improved to better understand the nature of the problem.

Can you please check if your application crashes with the plugin version 0.2.1?

**Closed** 2024-10-03 16:17 UTC

**Comment by Dwlad90** [comment] 2024-10-07 21:34
> This does fix that particular issue but we are running into others now unfortunately but can close this!

@pushchris,
If something still doesn't work for you or works incorrectly, then please open an issue and I will try to fix everything and bring the plugin to a stable working state.

Thank you for your help in developing the project🙂
